/wdqs_terms.sh Aegypten-Kiesel
./wdqs_terms.sh Smaragdpraser
./wdqs_terms.sh prime'
./wdqs_terms.sh 'd'Emeraude
./wdqs_terms.sh plasma+di+smeraldo+gemmario
./wdqs_terms.sh Chromium-Kalk
./wdqs_terms.sh Stangenstein
./wdqs_terms.sh Kreuzcrystall
./wdqs_terms.sh Schwererde
./wdqs_terms.sh Bitter-Erde
./wdqs_terms.sh Braunstein-Kalk
./wdqs_terms.sh Talck-Erde
./wdqs_terms.sh Eisengranat
./wdqs_terms.sh terra+argillosa
./wdqs_terms.sh terra+aluminosa
./wdqs_terms.sh Hornblendeschiefer
./wdqs_terms.sh Basaltische+Hornblends
./wdqs_terms.sh Field-spar
./wdqs_terms.sh smaragdite
./wdqs_terms.sh Portsoy-Granit
./wdqs_terms.sh Kiesel-Erde
./wdqs_terms.sh Töpferthon
./wdqs_terms.sh Schiefer-Thon
./wdqs_terms.sh Kohlenschiefer
./wdqs_terms.sh Schiftus+carbonarius
./wdqs_terms.sh lemnische-Erde
./wdqs_terms.sh Argilla+fullonum
./wdqs_terms.sh Alaun-Thon
./wdqs_terms.sh Alaun-Stein
./wdqs_terms.sh Alaun-Schiefer
./wdqs_terms.sh Kräuter-Schiefer
./wdqs_terms.sh Trilobiten-Schiefer
./wdqs_terms.sh Layenstein
./wdqs_terms.sh pietra+paragone
./wdqs_terms.sh Tafel-Schiefer
./wdqs_terms.sh Dach-Schiefer
./wdqs_terms.sh Kiesel-Schiefer
./wdqs_terms.sh Glimmer-Schiefer
./wdqs_terms.sh Tafel-Schiefer
./wdqs_terms.sh Zeichen-Schiefer
./wdqs_terms.sh Wetz-Schiefer
./wdqs_terms.sh Porphyrschiefers
./wdqs_terms.sh stonemarrow
./wdqs_terms.sh red-chalk
./wdqs_terms.sh Zeolieth
./wdqs_terms.sh Toadstone
./wdqs_terms.sh Tufwacke
./wdqs_terms.sh Talk-Erde
./wdqs_terms.sh Chlorit-Erde
./wdqs_terms.sh Sammet-Erde
./wdqs_terms.sh Chlorit-Erde
./wdqs_terms.sh Chlorit-Schiefer
./wdqs_terms.sh Talk-Schiefer
./wdqs_terms.sh Talcum+Venetum
./wdqs_terms.sh Leucaphrum
./wdqs_terms.sh Ecume+de+mer
./wdqs_terms.sh Schaum-Thon
./wdqs_terms.sh Killkeffi
./wdqs_terms.sh Talkerde
./wdqs_terms.sh pierre+de+lard
./wdqs_terms.sh Briançoner-Kreide
./wdqs_terms.sh verde+di+Corsica
./wdqs_terms.sh Bergflachs
./wdqs_terms.sh liége+fossile
./wdqs_terms.sh cuir+fossile
./wdqs_terms.sh schorl+rayonné
./wdqs_terms.sh Glasamianth
./wdqs_terms.sh grès+crystallisé
./wdqs_terms.sh Chernites
./wdqs_terms.sh Magnesites
./wdqs_terms.sh Spath+perlé
./wdqs_terms.sh alabastrites
./wdqs_terms.sh Mehlkreide
./wdqs_terms.sh Bergguhr
./wdqs_terms.sh bianco+antico
./wdqs_terms.sh Paro+antico
./wdqs_terms.sh Sandmarmor
./wdqs_terms.sh marmo+arenaceo
./wdqs_terms.sh marmor+tardum
./wdqs_terms.sh Ruinen-Marmor
./wdqs_terms.sh Dendriten-Marmor
./wdqs_terms.sh cittadino+ruderato
./wdqs_terms.sh Petrefacten-Marmor
./wdqs_terms.sh Muschel-Marmor
./wdqs_terms.sh Corallen-Marmor
./wdqs_terms.sh Breschen-Marmor
./wdqs_terms.sh Polzevera
./wdqs_terms.sh Cipollino+antico
./wdqs_terms.sh Hammites
./wdqs_terms.sh Thon-Mergel
./wdqs_terms.sh Mergel-Erde
./wdqs_terms.sh See-Conchylien
./wdqs_terms.sh Rhinocere
./wdqs_terms.sh Hammerkalk
./wdqs_terms.sh Medusen-Palme
./wdqs_terms.sh helmintholithus+portentosus
./wdqs_terms.sh ardaise+cuivreuse
./wdqs_terms.sh Frauen-Eis
./wdqs_terms.sh Gyps-Spath
./wdqs_terms.sh Gypssinter
./wdqs_terms.sh Gypsmehl
./wdqs_terms.sh Gypsguhr
./wdqs_terms.sh Himmelsmehl
./wdqs_terms.sh Gypsstein
./wdqs_terms.sh Gypsum+lamellosum
./wdqs_terms.sh Strahlgyps
./wdqs_terms.sh Gypsum+fibrosum
./wdqs_terms.sh Gypsum+densum
./wdqs_terms.sh Gyps-Leberstein
./wdqs_terms.sh Phosphor-Kalkstein
./wdqs_terms.sh Sedativspath
./wdqs_terms.sh Strontian-Erde
./wdqs_terms.sh carbonate+barytique
./wdqs_terms.sh sulfâte+barytique
./wdqs_terms.sh spat+pésant
./wdqs_terms.sh ponderous+spar
./wdqs_terms.sh Schwerspath-Erde
./wdqs_terms.sh Granito+rosso
./wdqs_terms.sh Feldspath-Avanturino
./wdqs_terms.sh Granit+feuilleté
./wdqs_terms.sh Granit+veiné
./wdqs_terms.sh porphido
./wdqs_terms.sh Quarz-Cäment
./wdqs_terms.sh Thon-Cäment
./wdqs_terms.sh Breschenschiefer
./wdqs_terms.sh Quarz-Cäment
./wdqs_terms.sh muriâte+de+soude
./wdqs_terms.sh Sal+ammoniacum
./wdqs_terms.sh Laugensalz
./wdqs_terms.sh sulfate+de+soude
./wdqs_terms.sh Magnesia+vitriolata
./wdqs_terms.sh sulfate+de+magnésie
./wdqs_terms.sh sulfate+dalumine'
./wdqs_terms.sh Keswick+lead
./wdqs_terms.sh Spiesglas
./wdqs_terms.sh Arsenik-Silber
./wdqs_terms.sh Spießglas-Silber
./wdqs_terms.sh argent+rouge
./wdqs_terms.sh vif-argent
./wdqs_terms.sh Jungfern-Quecksilber
./wdqs_terms.sh Quecksilber-Schwefelleber-Erz
./wdqs_terms.sh cinabre+alcalin
./wdqs_terms.sh Quecksilber-Leber-Erz
./wdqs_terms.sh Quecksiber-Leber-Erzes
./wdqs_terms.sh Corallen-Erzes
./wdqs_terms.sh Quecksilber-Erz

./wdqs_terms.sh Gabelgeyer
./wdqs_terms.sh Gad-fly
./wdqs_terms.sh Gagat
./wdqs_terms.sh Gallopavo
./wdqs_terms.sh Gallwespe
./wdqs_terms.sh Galmey
./wdqs_terms.sh Ganre
./wdqs_terms.sh Garneele
./wdqs_terms.sh Garzette
./wdqs_terms.sh Gäschtwurm
./wdqs_terms.sh Gastrobranchus
./wdqs_terms.sh Gelb-Erde
./wdqs_terms.sh Gelbgans
./wdqs_terms.sh Gelinotte
./wdqs_terms.sh Genettkatze
./wdqs_terms.sh Geschwäder
./wdqs_terms.sh Gestellstein
./wdqs_terms.sh Geyerkönig
./wdqs_terms.sh Gieskanne
./wdqs_terms.sh Giftkuttel
./wdqs_terms.sh Giftstein
./wdqs_terms.sh Glahrke
./wdqs_terms.sh Glanzerde
./wdqs_terms.sh Glas-Erde
./wdqs_terms.sh Glasstein
./wdqs_terms.sh Gobe+mouche
./wdqs_terms.sh Golddrossel
./wdqs_terms.sh Gold-finch
./wdqs_terms.sh Goldhahn
./wdqs_terms.sh Goldkarpfe
./wdqs_terms.sh Goldwurm
./wdqs_terms.sh Goose+ander
./wdqs_terms.sh Gotteslämmchen
./wdqs_terms.sh Graisset
./wdqs_terms.sh Grakle
./wdqs_terms.sh Granate
./wdqs_terms.sh Graphit
./wdqs_terms.sh Gras-hopper
./wdqs_terms.sh Grauwacken-Schiefer
./wdqs_terms.sh Grèbe
./wdqs_terms.sh Green-finch
./wdqs_terms.sh Grenouille+pecheuse
./wdqs_terms.sh Grès+crystallisée
./wdqs_terms.sh grönländische+Taube
./wdqs_terms.sh Grosbec
./wdqs_terms.sh grüne+Kreide
./wdqs_terms.sh grüner+Eisenstein
./wdqs_terms.sh grüner+Glimmer
./wdqs_terms.sh Grün-Erde
./wdqs_terms.sh Grüper
./wdqs_terms.sh Guepier
./wdqs_terms.sh Guineisches+Reh
./wdqs_terms.sh Guiney+pig
./wdqs_terms.sh Guiney-hen
./wdqs_terms.sh Gürtelthier
./wdqs_terms.sh Gypsspath
./wdqs_terms.sh Haarsalz
./wdqs_terms.sh Hadock
./wdqs_terms.sh Haferbock
./wdqs_terms.sh Hafft
./wdqs_terms.sh Hafpadde
./wdqs_terms.sh Hahnkamm
./wdqs_terms.sh Halbcaninchen
./wdqs_terms.sh Hammerfisch
./wdqs_terms.sh Hauben-Finke
./wdqs_terms.sh Haus-Teufel
./wdqs_terms.sh Haus-Unke
./wdqs_terms.sh Heckenschmatzer
./wdqs_terms.sh Heerschnepfe
./wdqs_terms.sh Heer-Wurm
./wdqs_terms.sh Heher
./wdqs_terms.sh Heimchen
./wdqs_terms.sh Helicit
./wdqs_terms.sh Heliotrop
./wdqs_terms.sh Helmed-fish
./wdqs_terms.sh Hérisson
./wdqs_terms.sh Herrenvogel
./wdqs_terms.sh Hetzle
./wdqs_terms.sh Heupferd
./wdqs_terms.sh Himmelsziege
./wdqs_terms.sh Hinnus
./wdqs_terms.sh Hirsch+Eder
./wdqs_terms.sh Holibut
./wdqs_terms.sh Holzemse
./wdqs_terms.sh Holzlaus
./wdqs_terms.sh Holzopal
./wdqs_terms.sh Holzspinne
./wdqs_terms.sh Holzstein
./wdqs_terms.sh Holz-Wespe
./wdqs_terms.sh Holz-Wurm
./wdqs_terms.sh Holz-Zinn
./wdqs_terms.sh Honig-Stein
./wdqs_terms.sh Hornerz
./wdqs_terms.sh Hornfisch
./wdqs_terms.sh Hornschiefer
./wdqs_terms.sh Huitrier
./wdqs_terms.sh Humming+bird
./wdqs_terms.sh Hyaena+odorifera
./wdqs_terms.sh Hyalit
./wdqs_terms.sh Hydrachna
./wdqs_terms.sh Hydrocalcedoine
./wdqs_terms.sh Hydrocantharus
./wdqs_terms.sh Hydrophan
./wdqs_terms.sh Ignavus
./wdqs_terms.sh Iguana
./wdqs_terms.sh Immewolf
./wdqs_terms.sh indianische+Vogelnester
./wdqs_terms.sh indianischer+Rabe
./wdqs_terms.sh indianischer+Speck
./wdqs_terms.sh Infusionsthierchen
./wdqs_terms.sh Ink+fish
./wdqs_terms.sh isländischer+Achat
./wdqs_terms.sh isländischer+Crystall
./wdqs_terms.sh Jacapa
./wdqs_terms.sh Jacobine
./wdqs_terms.sh Jaseur
./wdqs_terms.sh Jeay
./wdqs_terms.sh Jochfisch
./wdqs_terms.sh Johannis-Blut
./wdqs_terms.sh Johannis-Würmchen
./wdqs_terms.sh Jointed+worm
./wdqs_terms.sh Juda-Schlange
./wdqs_terms.sh Juden-Pech
./wdqs_terms.sh Juden-Stein
./wdqs_terms.sh Jupujuba
./wdqs_terms.sh Juwelen-Käfer
./wdqs_terms.sh Kackerlacke
./wdqs_terms.sh Kahau
./wdqs_terms.sh Kalekuter
./wdqs_terms.sh Kalmückenachat
./wdqs_terms.sh Kamichy
./wdqs_terms.sh Kämmelthier
./wdqs_terms.sh Kamm-Muschel
./wdqs_terms.sh Kampf-Hahn
./wdqs_terms.sh Karausche
./wdqs_terms.sh Karechel
./wdqs_terms.sh Kaschelong
./wdqs_terms.sh Kascholong
./wdqs_terms.sh Katzenauge
./wdqs_terms.sh Kaul-Bars
./wdqs_terms.sh Käutzlein
./wdqs_terms.sh Kefekil
./wdqs_terms.sh Kelleresel
./wdqs_terms.sh Kernbeisser
./wdqs_terms.sh Keswick-lead
./wdqs_terms.sh Kiefenfuß
./wdqs_terms.sh Kieselsinter
./wdqs_terms.sh Kingsfisher
./wdqs_terms.sh Kinkhorn
./wdqs_terms.sh Kirschfink
./wdqs_terms.sh Kirschvogel
./wdqs_terms.sh Klapperstein
./wdqs_terms.sh Klebpfost
./wdqs_terms.sh Kleisteraal
./wdqs_terms.sh Kliesche
./wdqs_terms.sh Klipprose
./wdqs_terms.sh Klosterwenzel
./wdqs_terms.sh Klumpfisch
./wdqs_terms.sh Knurrhahn
./wdqs_terms.sh Kohlenblende
./wdqs_terms.sh Kolumbachische+Mücke
./wdqs_terms.sh Korkorre
./wdqs_terms.sh Kornferkel
./wdqs_terms.sh Kornwurm
./wdqs_terms.sh Kothbahn
./wdqs_terms.sh Kothhahn
./wdqs_terms.sh Krametsvogel
./wdqs_terms.sh Krampffisch
./wdqs_terms.sh Kräuselschnecke
./wdqs_terms.sh Kräuterschiefer
./wdqs_terms.sh Kronvogel
./wdqs_terms.sh Kröpfer
./wdqs_terms.sh Kropfgans
./wdqs_terms.sh Krünitz
./wdqs_terms.sh Kuckuk
./wdqs_terms.sh Kuckukspeichel
./wdqs_terms.sh Kugelthier
./wdqs_terms.sh Kümmelkäfer
./wdqs_terms.sh Kupferwasser
./wdqs_terms.sh Kürbskernwürmer
./wdqs_terms.sh Kuttelfisch
./wdqs_terms.sh Labradorstein
./wdqs_terms.sh Lacert
./wdqs_terms.sh Lackwurm
./wdqs_terms.sh Lady+cow
./wdqs_terms.sh Lämmergeyer
./wdqs_terms.sh Lamprete
./wdqs_terms.sh Lamproye
./wdqs_terms.sh Lanthorn-fly
./wdqs_terms.sh Lapis+acerosus
./wdqs_terms.sh Lapis+bononiensis
./wdqs_terms.sh Lapis+calaminaris
./wdqs_terms.sh Lapis+comensis
./wdqs_terms.sh Lapis+hepaticus
./wdqs_terms.sh Lapis+inolithus
./wdqs_terms.sh Lapis+muriaticus
./wdqs_terms.sh Lapis+numularis
./wdqs_terms.sh Lapis+spongiae
./wdqs_terms.sh Laternträger
./wdqs_terms.sh Lavaglas
./wdqs_terms.sh Lavandiere
./wdqs_terms.sh Lavezzstein
./wdqs_terms.sh Lazarusklappe
./wdqs_terms.sh Leber-Erz
./wdqs_terms.sh Leberkies
./wdqs_terms.sh Leberstein
./wdqs_terms.sh Lenticulit
./wdqs_terms.sh Lepidolith
./wdqs_terms.sh Letterschulpe
./wdqs_terms.sh Leyermann
./wdqs_terms.sh Lezard
./wdqs_terms.sh Lievre
./wdqs_terms.sh Lievre+de+mer
./wdqs_terms.sh Ligurinus
./wdqs_terms.sh Lilienkäfer
./wdqs_terms.sh Lillalit
./wdqs_terms.sh Limus
./wdqs_terms.sh Linkshörnchen
./wdqs_terms.sh Linote
./wdqs_terms.sh Linotte
./wdqs_terms.sh Linsen-Erz
./wdqs_terms.sh Linsenstein
./wdqs_terms.sh Lithantrax
./wdqs_terms.sh Lithomarga
./wdqs_terms.sh Litorne
./wdqs_terms.sh litte+old+wife
./wdqs_terms.sh Llacma
./wdqs_terms.sh Load-stone
./wdqs_terms.sh Loche
./wdqs_terms.sh Löffelgans
./wdqs_terms.sh Loup-cervier
./wdqs_terms.sh Loutre
./wdqs_terms.sh Löwe
./wdqs_terms.sh Ludus+Helmontii
./wdqs_terms.sh Lumacchella
./wdqs_terms.sh Lumer
./wdqs_terms.sh Lydischer+Stein
./wdqs_terms.sh Macacco
./wdqs_terms.sh Mackukawa
./wdqs_terms.sh Macku-Kawa
./wdqs_terms.sh Maçonne
./wdqs_terms.sh Madenwurm
./wdqs_terms.sh Main+de+ladre
./wdqs_terms.sh Mainate
./wdqs_terms.sh Maisdieb
./wdqs_terms.sh Makkukawa
./wdqs_terms.sh Mak-kukwa
./wdqs_terms.sh Mammutsknochen
./wdqs_terms.sh Manacanie
./wdqs_terms.sh Manacanit
./wdqs_terms.sh Manate
./wdqs_terms.sh Manche+de+couteau
./wdqs_terms.sh Manucodiatta
./wdqs_terms.sh Manus+marina
./wdqs_terms.sh Marcasit
./wdqs_terms.sh Marcolph
./wdqs_terms.sh Marekanstein
./wdqs_terms.sh Martin+pecheur
./wdqs_terms.sh Mastwurm
./wdqs_terms.sh Mauerspecht
./wdqs_terms.sh Maulthier
./wdqs_terms.sh Maulwurfgrille
./wdqs_terms.sh Mauvis
./wdqs_terms.sh Mayfisch
./wdqs_terms.sh Maykäfer
./wdqs_terms.sh Maywurm
./wdqs_terms.sh Medusenpalme
./wdqs_terms.sh Meer-Barbe
./wdqs_terms.sh Meerbohne
./wdqs_terms.sh Meer-Bohne
./wdqs_terms.sh Meergrundel
./wdqs_terms.sh Meerjunker
./wdqs_terms.sh Meerkatze
./wdqs_terms.sh Meernadel
./wdqs_terms.sh Meer-Nadel
./wdqs_terms.sh Meernessel
./wdqs_terms.sh Meerschnepfe
./wdqs_terms.sh Meer-Schnepfe
./wdqs_terms.sh Meer-Schweinchen
./wdqs_terms.sh Meertulpe
./wdqs_terms.sh Meerzahn
./wdqs_terms.sh Meer-Zahn
./wdqs_terms.sh Mehlthau
./wdqs_terms.sh Mehlwurm
./wdqs_terms.sh Melanit
./wdqs_terms.sh Melone+v+Berg+Carmel
./wdqs_terms.sh Mergvs
./wdqs_terms.sh Merlan
./wdqs_terms.sh Mesange
./wdqs_terms.sh Messerfisch
./wdqs_terms.sh Mestisse
./wdqs_terms.sh Mestiße
./wdqs_terms.sh Millepied+deau
./wdqs_terms.sh kalkartiges+Gestein
./wdqs_terms.sh Kalkröhrenwurm
./wdqs_terms.sh LAigle
./wdqs_terms.sh Tomback
./wdqs_terms.sh blanc+dEspagne
./wdqs_terms.sh mine+de+cuivre+vitreuse
./wdqs_terms.sh Calabassen-Kürbisse
./wdqs_terms.sh Calmücken
./wdqs_terms.sh Cameelen
./wdqs_terms.sh Camele
./wdqs_terms.sh camérine
./wdqs_terms.sh Canarienvögeln
./wdqs_terms.sh Caninchen
./wdqs_terms.sh capitulum
./wdqs_terms.sh carabé
./wdqs_terms.sh Carassus
./wdqs_terms.sh carbonate+barytique
./wdqs_terms.sh carbonate+de+soude
./wdqs_terms.sh cardinal+pourpré
./wdqs_terms.sh carex+caespitosa
./wdqs_terms.sh carlina+acaulis
./wdqs_terms.sh Carminhänfling
./wdqs_terms.sh Carmoisin-Schlange
./wdqs_terms.sh Casacken
./wdqs_terms.sh Caßawi-Wurzel
./wdqs_terms.sh Caschicame
./wdqs_terms.sh casse+noix
./wdqs_terms.sh Cassine
./wdqs_terms.sh casuarina+equisetifolia
./wdqs_terms.sh cauda+prehensilis
./wdqs_terms.sh cauda+saltatoria
./wdqs_terms.sh centipellio
./wdqs_terms.sh charbonniere
./wdqs_terms.sh chassinch
./wdqs_terms.sh chauvesouris
./wdqs_terms.sh Chernites
./wdqs_terms.sh cheuvrette
./wdqs_terms.sh chien-loup
./wdqs_terms.sh Chlorit-Erde
./wdqs_terms.sh Chlorit-Schiefer
./wdqs_terms.sh chorion
./wdqs_terms.sh Chromium-Erz
./wdqs_terms.sh Chromium-Kalk
./wdqs_terms.sh Chysopras
./wdqs_terms.sh cicogne
./wdqs_terms.sh cicogne+du+Bresil
./wdqs_terms.sh cinabre+alcalin
./wdqs_terms.sh Cipollino+antico
./wdqs_terms.sh Cirkelmotte
./wdqs_terms.sh Citronen-Papilion
./wdqs_terms.sh cittadino+ruderato
./wdqs_terms.sh clauariae
./wdqs_terms.sh Coaita
./wdqs_terms.sh Cochenillwürmer
./wdqs_terms.sh COCHLEAE
./wdqs_terms.sh Colibrite
./wdqs_terms.sh Colophoniumblende
./wdqs_terms.sh Coneparl
./wdqs_terms.sh Contreadmiral
./wdqs_terms.sh conuoluulus+batatas
./wdqs_terms.sh coq+et+la+poule
./wdqs_terms.sh coquille+de+nacre
./wdqs_terms.sh coquille+porte+foie
./wdqs_terms.sh Corallen-Erzes
./wdqs_terms.sh Corallen-Marmor
./wdqs_terms.sh Corneol
./wdqs_terms.sh Cornutus
./wdqs_terms.sh Corsicanerhunde
./wdqs_terms.sh cotyledones
./wdqs_terms.sh couperose+blanche
./wdqs_terms.sh couperose+bleue
./wdqs_terms.sh couperose+verte
./wdqs_terms.sh crayon+dAngleterre
./wdqs_terms.sh Bunt-Kupfer-Erz
./wdqs_terms.sh Kupfer-Erz
./wdqs_terms.sh mine+de+cuivre+jaune
./wdqs_terms.sh mine+de+cuivre'
./wdqs_terms.sh 'blanche
./wdqs_terms.sh muriate+de+cuivre+oxygené
./wdqs_terms.sh sable+verd+dAtacama'
./wdqs_terms.sh Becasse
./wdqs_terms.sh Beccafige
./wdqs_terms.sh Beinbrecher
./wdqs_terms.sh Beißfliege
./wdqs_terms.sh Belemnit
./wdqs_terms.sh Bell-metal+arc
./wdqs_terms.sh Benitier
./wdqs_terms.sh Berg+Theer
./wdqs_terms.sh Bergaelster
./wdqs_terms.sh Bergbalsam
./wdqs_terms.sh Bergbutter
./wdqs_terms.sh Bergcrystall
./wdqs_terms.sh Bergseife
./wdqs_terms.sh Bergzieger
./wdqs_terms.sh Beril+feuilleté
./wdqs_terms.sh Bête+de+la+vierge
./wdqs_terms.sh Beutel-Meise
./wdqs_terms.sh Beutelratte
./wdqs_terms.sh biegsamer+Sandstein
./wdqs_terms.sh Biene
./wdqs_terms.sh Birkheher
./wdqs_terms.sh Bisamratze
./wdqs_terms.sh Bisamthier
./wdqs_terms.sh Bittersalzspath
./wdqs_terms.sh Bittersalzstein
./wdqs_terms.sh Bitume+de+Judee
./wdqs_terms.sh bituminöser+Mergelschiefer
./wdqs_terms.sh bituminöses+Holz
./wdqs_terms.sh Black+beetle
./wdqs_terms.sh Black+beetle+bird
./wdqs_terms.sh Black+beetle+cap
./wdqs_terms.sh Black+beetle+cock
./wdqs_terms.sh Black+beetle+jack
./wdqs_terms.sh Black+beetle+lead
./wdqs_terms.sh Blackfisch
./wdqs_terms.sh Blasenschnecke
./wdqs_terms.sh Blasenschneckenwurm
./wdqs_terms.sh Blaßhuhn
./wdqs_terms.sh Blatta+byzantina
./wdqs_terms.sh Blättererz
./wdqs_terms.sh Blatt-Käfer
./wdqs_terms.sh Blatt-Käferlaus
./wdqs_terms.sh Blatt-Käfersauger
./wdqs_terms.sh Blatt-Käferwespe
./wdqs_terms.sh Blaumüller
./wdqs_terms.sh Blauspecht
./wdqs_terms.sh Blindfisch
./wdqs_terms.sh Blumenpolype
./wdqs_terms.sh Blumenspecht
./wdqs_terms.sh Blut-Igel
./wdqs_terms.sh Boat+bill
./wdqs_terms.sh Bohnen-Erz
./wdqs_terms.sh Bohrmuschel
./wdqs_terms.sh Bologneserstein
./wdqs_terms.sh Bombardirkäfer
./wdqs_terms.sh Bonite
./wdqs_terms.sh Boracit
./wdqs_terms.sh Borech
./wdqs_terms.sh Bout+de+petun
./wdqs_terms.sh Bouvreuil
./wdqs_terms.sh Braun-Erz
./wdqs_terms.sh Braunspath
./wdqs_terms.sh Briançoner+Kreide
./wdqs_terms.sh Bücherscorpion
./wdqs_terms.sh Bufonit
./wdqs_terms.sh Bull-finch
./wdqs_terms.sh Buphaga
./wdqs_terms.sh Butter-fly
./wdqs_terms.sh Buttermilch-Erz
./wdqs_terms.sh Buttervogel
./wdqs_terms.sh Buzz-fly
./wdqs_terms.sh Byrrhus
./wdqs_terms.sh Cachicame
./wdqs_terms.sh Caddice
./wdqs_terms.sh Caillon+dEgypte'
./wdqs_terms.sh Cuntur
./wdqs_terms.sh Curasso
./wdqs_terms.sh Curucutu
./wdqs_terms.sh Cut+water
./wdqs_terms.sh Cuthberts+beads
./wdqs_terms.sh Dactylus+idaeus
./wdqs_terms.sh Daker-hen
./wdqs_terms.sh Darmröhre
./wdqs_terms.sh das+wandelnde+Blatt
./wdqs_terms.sh Dattelmuschel
./wdqs_terms.sh Demant
./wdqs_terms.sh Demantspath
./wdqs_terms.sh Dendrachat
./wdqs_terms.sh Diable+de+mer
./wdqs_terms.sh Diebs-Hand
./wdqs_terms.sh Dohmpfaff
./wdqs_terms.sh Doppelspath
./wdqs_terms.sh Drap+dor
./wdqs_terms.sh Colophoniumblende
./wdqs_terms.sh marcasita+officinalis
./wdqs_terms.sh étain+de+glace
./wdqs_terms.sh tin-glass
./wdqs_terms.sh blanc+dEspagne
./wdqs_terms.sh bohemian+chatterer
./wdqs_terms.sh jaseur+de+Boheme
./wdqs_terms.sh pinçon+dArdennes