./wdqs_terms_english.sh iron
./wdqs_terms_english.sh Acorn+shell
./wdqs_terms_english.sh acron
./wdqs_terms_english.sh adder
./wdqs_terms_english.sh Amber
./wdqs_terms_english.sh Amedabad+finch
./wdqs_terms_english.sh amzell
./wdqs_terms_english.sh Ant
./wdqs_terms_english.sh Ant+eater
./wdqs_terms_english.sh ant+eater
./wdqs_terms_english.sh arsenical+mundick
./wdqs_terms_english.sh Atrypa
./wdqs_terms_english.sh Auk
./wdqs_terms_english.sh Baboon
./wdqs_terms_english.sh Badger
./wdqs_terms_english.sh barbadoes+millet
./wdqs_terms_english.sh Barnacle
./wdqs_terms_english.sh Bat
./wdqs_terms_english.sh Bear
./wdqs_terms_english.sh beauty
./wdqs_terms_english.sh Beaver
./wdqs_terms_english.sh Bee
./wdqs_terms_english.sh Bee+eater
./wdqs_terms_english.sh bee+eater
./wdqs_terms_english.sh Beef+eater
./wdqs_terms_english.sh beefeater
./wdqs_terms_english.sh Beetle
./wdqs_terms_english.sh Bell+metal+arc
./wdqs_terms_english.sh Bivalve
./wdqs_terms_english.sh black+cap
./wdqs_terms_english.sh Black+beetle
./wdqs_terms_english.sh Black+beetle+bird
./wdqs_terms_english.sh Black+beetle+cap
./wdqs_terms_english.sh Black+beetle+cock
./wdqs_terms_english.sh Black+beetle+jack
./wdqs_terms_english.sh Black+beetle+lead
./wdqs_terms_english.sh black+cock
./wdqs_terms_english.sh black+eagle
./wdqs_terms_english.sh black+jack
./wdqs_terms_english.sh black+lead
./wdqs_terms_english.sh black+martin
./wdqs_terms_english.sh black+wad
./wdqs_terms_english.sh blackbird
./wdqs_terms_english.sh blackmoor's+teeth
./wdqs_terms_english.sh Bleak
./wdqs_terms_english.sh blind+worm
./wdqs_terms_english.sh Blindworm
./wdqs_terms_english.sh blubber
./wdqs_terms_english.sh blue+lead+ore
./wdqs_terms_english.sh Boat+bill
./wdqs_terms_english.sh boatbill
./wdqs_terms_english.sh bohemian+chatterer
./wdqs_terms_english.sh Bootshake
./wdqs_terms_english.sh Botts
./wdqs_terms_english.sh Boveycoal
./wdqs_terms_english.sh Bramble
./wdqs_terms_english.sh breeze
./wdqs_terms_english.sh Brimstone
./wdqs_terms_english.sh brown+owl
./wdqs_terms_english.sh Bug
./wdqs_terms_english.sh bull+dog
./wdqs_terms_english.sh Bull+finch
./wdqs_terms_english.sh bull+frog
./wdqs_terms_english.sh bull+head
./wdqs_terms_english.sh bullfinch
./wdqs_terms_english.sh Bullfrog
./wdqs_terms_english.sh Bullhead
./wdqs_terms_english.sh Bunting
./wdqs_terms_english.sh Burbot
./wdqs_terms_english.sh Bustard
./wdqs_terms_english.sh Butter+fly
./wdqs_terms_english.sh butterfly
./wdqs_terms_english.sh button+shell
./wdqs_terms_english.sh Buzz+fly
./wdqs_terms_english.sh Caddice
./wdqs_terms_english.sh Calamine
./wdqs_terms_english.sh caltrop
./wdqs_terms_english.sh Camel
./wdqs_terms_english.sh Cancer
./wdqs_terms_english.sh Cannel+coal
./wdqs_terms_english.sh Capelin
./wdqs_terms_english.sh carp
./wdqs_terms_english.sh carrier+pigeon
./wdqs_terms_english.sh Cat
./wdqs_terms_english.sh Cawk
./wdqs_terms_english.sh Chaffinch
./wdqs_terms_english.sh Chalk
./wdqs_terms_english.sh chassinch
./wdqs_terms_english.sh Chatterer
./wdqs_terms_english.sh Chert
./wdqs_terms_english.sh chimney+swallow
./wdqs_terms_english.sh Clam
./wdqs_terms_english.sh Coal
./wdqs_terms_english.sh Cochineal+fly
./wdqs_terms_english.sh Cochinealfly
./wdqs_terms_english.sh Cock
./wdqs_terms_english.sh Cock+of+the+wood
./wdqs_terms_english.sh cock+of+the+wood
./wdqs_terms_english.sh Cockle
./wdqs_terms_english.sh Cockroach
./wdqs_terms_english.sh cod+fish
./wdqs_terms_english.sh Codfish
./wdqs_terms_english.sh Coot
./wdqs_terms_english.sh copper
./wdqs_terms_english.sh Cormoran
./wdqs_terms_english.sh cowry
./wdqs_terms_english.sh Cowry+shell
./wdqs_terms_english.sh Crab
./wdqs_terms_english.sh crab+louse
./wdqs_terms_english.sh Crablouse
./wdqs_terms_english.sh Crampfish
./wdqs_terms_english.sh Crane+fly
./wdqs_terms_english.sh Craue
./wdqs_terms_english.sh craw+fish
./wdqs_terms_english.sh Creeper
./wdqs_terms_english.sh Cricket
./wdqs_terms_english.sh cropper+pigeon
./wdqs_terms_english.sh Cross+bill
./wdqs_terms_english.sh cross+bill
./wdqs_terms_english.sh Crow
./wdqs_terms_english.sh Crow+fish
./wdqs_terms_english.sh Crucian
./wdqs_terms_english.sh Crucifix
./wdqs_terms_english.sh Cuckow
./wdqs_terms_english.sh cur
./wdqs_terms_english.sh Cut+water
./wdqs_terms_english.sh Cuthbert's+beads
./wdqs_terms_english.sh Cuthbert's+duck
./wdqs_terms_english.sh Dab
./wdqs_terms_english.sh Daker+hen
./wdqs_terms_english.sh Dakerhen
./wdqs_terms_english.sh Death+watch
./wdqs_terms_english.sh dew+worm
./wdqs_terms_english.sh Diamond
./wdqs_terms_english.sh Dipper
./wdqs_terms_english.sh Dog
./wdqs_terms_english.sh dolphin
./wdqs_terms_english.sh doree
./wdqs_terms_english.sh Dormouse
./wdqs_terms_english.sh Dory
./wdqs_terms_english.sh Dove
./wdqs_terms_english.sh Dragon+fly
./wdqs_terms_english.sh Duck
./wdqs_terms_english.sh Dudley+fossil
./wdqs_terms_english.sh dung+beetle
./wdqs_terms_english.sh Eagle
./wdqs_terms_english.sh eagle+owl
./wdqs_terms_english.sh Ear+wig
./wdqs_terms_english.sh ear+wig
./wdqs_terms_english.sh Earth+worm
./wdqs_terms_english.sh earth+worm
./wdqs_terms_english.sh Eel
./wdqs_terms_english.sh Eiderduck
./wdqs_terms_english.sh Elaterites
./wdqs_terms_english.sh Elk
./wdqs_terms_english.sh Elke
./wdqs_terms_english.sh emery
./wdqs_terms_english.sh Epigenesis
./wdqs_terms_english.sh Ermine
./wdqs_terms_english.sh étain+sulfureux
./wdqs_terms_english.sh extraneous+fossils
./wdqs_terms_english.sh fairiesfingers
./wdqs_terms_english.sh falcon
./wdqs_terms_english.sh Fallow+deer
./wdqs_terms_english.sh Ferret
./wdqs_terms_english.sh field+mouse
./wdqs_terms_english.sh field+rat
./wdqs_terms_english.sh Field+spar
./wdqs_terms_english.sh Fieldfare
./wdqs_terms_english.sh fieldlark
./wdqs_terms_english.sh fieldsare
./wdqs_terms_english.sh Fitchet
./wdqs_terms_english.sh Flair
./wdqs_terms_english.sh Flea
./wdqs_terms_english.sh Flint
./wdqs_terms_english.sh Flounder
./wdqs_terms_english.sh flow+worm
./wdqs_terms_english.sh Fluke
./wdqs_terms_english.sh Fly
./wdqs_terms_english.sh Fly+catcher
./wdqs_terms_english.sh flycatcher
./wdqs_terms_english.sh Foetus
./wdqs_terms_english.sh fossile+Tar
./wdqs_terms_english.sh Fox
./wdqs_terms_english.sh Frog
./wdqs_terms_english.sh frog+filsh
./wdqs_terms_english.sh Fuller's+earth
./wdqs_terms_english.sh Gad+fly
./wdqs_terms_english.sh Galibi+stone
./wdqs_terms_english.sh Gannet
./wdqs_terms_english.sh Gaper
./wdqs_terms_english.sh Garpike
./wdqs_terms_english.sh Gavial
./wdqs_terms_english.sh Glow+worm
./wdqs_terms_english.sh glow+worm
./wdqs_terms_english.sh Glutton
./wdqs_terms_english.sh Gnat
./wdqs_terms_english.sh Goat
./wdqs_terms_english.sh Goat+sucker
./wdqs_terms_english.sh goatsucker
./wdqs_terms_english.sh Gold+finch
./wdqs_terms_english.sh golden+eagle
./wdqs_terms_english.sh golden+fly
./wdqs_terms_english.sh goldfinch
./wdqs_terms_english.sh goldfish
./wdqs_terms_english.sh goos+ander
./wdqs_terms_english.sh Goose
./wdqs_terms_english.sh Goose+ander
./wdqs_terms_english.sh Goose+hawk
./wdqs_terms_english.sh goosehawk
./wdqs_terms_english.sh Grakle
./wdqs_terms_english.sh Grampus
./wdqs_terms_english.sh grand+aigle
./wdqs_terms_english.sh Gras+hopper
./wdqs_terms_english.sh grashopper
./wdqs_terms_english.sh great+hornowl
./wdqs_terms_english.sh great+shrike
./wdqs_terms_english.sh greater+linnet
./wdqs_terms_english.sh green+sparrow
./wdqs_terms_english.sh Green+finch
./wdqs_terms_english.sh greenfinch
./wdqs_terms_english.sh grey+hound
./wdqs_terms_english.sh grey+copper+ore
./wdqs_terms_english.sh Grous
./wdqs_terms_english.sh Guinea+pig
./wdqs_terms_english.sh guiney+hen
./wdqs_terms_english.sh Guiney+pig
./wdqs_terms_english.sh Guiney+hen
./wdqs_terms_english.sh Gull
./wdqs_terms_english.sh Hadock
./wdqs_terms_english.sh Haematites
./wdqs_terms_english.sh Hair+worm
./wdqs_terms_english.sh hairworm
./wdqs_terms_english.sh Hare
./wdqs_terms_english.sh Hawfinch
./wdqs_terms_english.sh Hedge+hog
./wdqs_terms_english.sh Hedge+sparrow
./wdqs_terms_english.sh hedge+hog
./wdqs_terms_english.sh Helmed+fish
./wdqs_terms_english.sh hen
./wdqs_terms_english.sh Heron
./wdqs_terms_english.sh Hog
./wdqs_terms_english.sh Holibut
./wdqs_terms_english.sh horn+of+plenty
./wdqs_terms_english.sh Hornet
./wdqs_terms_english.sh hornowl
./wdqs_terms_english.sh Horse
./wdqs_terms_english.sh Horse+leech
./wdqs_terms_english.sh Horse+shoe
./wdqs_terms_english.sh horse+shoe
./wdqs_terms_english.sh horseleech
./wdqs_terms_english.sh house+swallow
./wdqs_terms_english.sh Humble+bee
./wdqs_terms_english.sh Humming+bird
./wdqs_terms_english.sh indian+tourtle
./wdqs_terms_english.sh Ink+fish
./wdqs_terms_english.sh Ink.+fish
./wdqs_terms_english.sh Izard
./wdqs_terms_english.sh Jackdaw
./wdqs_terms_english.sh Jacobine
./wdqs_terms_english.sh Jay
./wdqs_terms_english.sh Jayet
./wdqs_terms_english.sh Jet
./wdqs_terms_english.sh Jointed+worm
./wdqs_terms_english.sh jointed+worm
./wdqs_terms_english.sh Jumar
./wdqs_terms_english.sh Keswick+lead
./wdqs_terms_english.sh Keswick+lead
./wdqs_terms_english.sh Kingsfisher
./wdqs_terms_english.sh Kite
./wdqs_terms_english.sh Lady+cow
./wdqs_terms_english.sh Lady+bird
./wdqs_terms_english.sh Lady+cow
./wdqs_terms_english.sh Lamprey
./wdqs_terms_english.sh Lanthorn+fly
./wdqs_terms_english.sh lap+dog
./wdqs_terms_english.sh Lapwing
./wdqs_terms_english.sh Lark
./wdqs_terms_english.sh lead
./wdqs_terms_english.sh Leech
./wdqs_terms_english.sh Leimen
./wdqs_terms_english.sh Leopard+cowry+shell
./wdqs_terms_english.sh lesser+linnet
./wdqs_terms_english.sh Limpet
./wdqs_terms_english.sh Linnet
./wdqs_terms_english.sh Lion
./wdqs_terms_english.sh litte+old+wife
./wdqs_terms_english.sh little+owl
./wdqs_terms_english.sh Lizard
./wdqs_terms_english.sh Load+stone
./wdqs_terms_english.sh Loam
./wdqs_terms_english.sh Lobster
./wdqs_terms_english.sh Louse
./wdqs_terms_english.sh Lumpsucker
./wdqs_terms_english.sh Mackrel
./wdqs_terms_english.sh Madrepore
./wdqs_terms_english.sh Magpie
./wdqs_terms_english.sh Man+of+war
./wdqs_terms_english.sh Manakin
./wdqs_terms_english.sh Marle
./wdqs_terms_english.sh Martin
./wdqs_terms_english.sh mastiff
./wdqs_terms_english.sh Menorrhagia
./wdqs_terms_english.sh Miller's+thumb
./wdqs_terms_english.sh Millers+thumb
./wdqs_terms_english.sh Minow
./wdqs_terms_english.sh missel+bird
./wdqs_terms_english.sh Missel+bird
./wdqs_terms_english.sh mock+bird
./wdqs_terms_english.sh Mock+bird
./wdqs_terms_english.sh Mole
./wdqs_terms_english.sh Moon+fish
./wdqs_terms_english.sh Moose+deer
./wdqs_terms_english.sh Moth
./wdqs_terms_english.sh mother+cary's+chicken
./wdqs_terms_english.sh Mountain+cat
./wdqs_terms_english.sh Mouse
./wdqs_terms_english.sh Mundick
./wdqs_terms_english.sh muscle
./wdqs_terms_english.sh Musk
./wdqs_terms_english.sh musk+ox
./wdqs_terms_english.sh Mussel
./wdqs_terms_english.sh Night+raven
./wdqs_terms_english.sh Nightingale
./wdqs_terms_english.sh nun
./wdqs_terms_english.sh nut+cracker
./wdqs_terms_english.sh Nut+cracker
./wdqs_terms_english.sh Nut+hatch
./wdqs_terms_english.sh oil+beetle
./wdqs_terms_english.sh Oil+heetle
./wdqs_terms_english.sh Old+wife
./wdqs_terms_english.sh Osprey
./wdqs_terms_english.sh Ostrich
./wdqs_terms_english.sh Owl
./wdqs_terms_english.sh Ox
./wdqs_terms_english.sh Oyster
./wdqs_terms_english.sh Oyster+catcher
./wdqs_terms_english.sh oyster+catcher
./wdqs_terms_english.sh paper+sailor
./wdqs_terms_english.sh Parrot
./wdqs_terms_english.sh Partridge
./wdqs_terms_english.sh Peacock
./wdqs_terms_english.sh Peat
./wdqs_terms_english.sh perch
./wdqs_terms_english.sh periwincle
./wdqs_terms_english.sh Petechiae
./wdqs_terms_english.sh Pheasant
./wdqs_terms_english.sh Phytolith
./wdqs_terms_english.sh pierce+stone
./wdqs_terms_english.sh Pigeon
./wdqs_terms_english.sh Pike
./wdqs_terms_english.sh pine+martin
./wdqs_terms_english.sh Pipe
./wdqs_terms_english.sh Piper
./wdqs_terms_english.sh Plaise
./wdqs_terms_english.sh Plant+louse
./wdqs_terms_english.sh plover
./wdqs_terms_english.sh Pogge
./wdqs_terms_english.sh pol+cat
./wdqs_terms_english.sh Pole+cat
./wdqs_terms_english.sh polecat
./wdqs_terms_english.sh ponderous+spar
./wdqs_terms_english.sh Porcupine
./wdqs_terms_english.sh Porcupine+fish
./wdqs_terms_english.sh porcupine+fish
./wdqs_terms_english.sh Porpesse
./wdqs_terms_english.sh Porpoise
./wdqs_terms_english.sh Portuguese+man+of+war
./wdqs_terms_english.sh Puffin
./wdqs_terms_english.sh pugdog
./wdqs_terms_english.sh pumice+stone
./wdqs_terms_english.sh Punger
./wdqs_terms_english.sh Quartz
./wdqs_terms_english.sh quicksilver
./wdqs_terms_english.sh Rabbet
./wdqs_terms_english.sh rabbit
./wdqs_terms_english.sh Rackun
./wdqs_terms_english.sh Rail
./wdqs_terms_english.sh Rat
./wdqs_terms_english.sh Rattle+snake
./wdqs_terms_english.sh Raven
./wdqs_terms_english.sh Ravenous
./wdqs_terms_english.sh Razor+shell
./wdqs_terms_english.sh Red+bird
./wdqs_terms_english.sh red+bird
./wdqs_terms_english.sh Red+breast
./wdqs_terms_english.sh Red+chalk
./wdqs_terms_english.sh red+cork+like+wad
./wdqs_terms_english.sh Red+start
./wdqs_terms_english.sh Red+wing
./wdqs_terms_english.sh red+backed+shrike
./wdqs_terms_english.sh red+breasted+blackbird
./wdqs_terms_english.sh red+chalk
./wdqs_terms_english.sh redstart
./wdqs_terms_english.sh redwing
./wdqs_terms_english.sh rellmouse
./wdqs_terms_english.sh REPTILES
./wdqs_terms_english.sh Rere+mouse
./wdqs_terms_english.sh Reremouse
./wdqs_terms_english.sh Rhomb+shell
./wdqs_terms_english.sh ring+dove
./wdqs_terms_english.sh rock+shell
./wdqs_terms_english.sh Roe
./wdqs_terms_english.sh Roller
./wdqs_terms_english.sh Rook
./wdqs_terms_english.sh rough+sooted
./wdqs_terms_english.sh dove
./wdqs_terms_english.sh round+worm
./wdqs_terms_english.sh Round+worm
./wdqs_terms_english.sh Ruby+ore
./wdqs_terms_english.sh Ruff
./wdqs_terms_english.sh Ruffe
./wdqs_terms_english.sh Rype
./wdqs_terms_english.sh Sable
./wdqs_terms_english.sh sailor
./wdqs_terms_english.sh salmon
./wdqs_terms_english.sh Sand+launce
./wdqs_terms_english.sh Sand+launce
./wdqs_terms_english.sh sandkrab
./wdqs_terms_english.sh sandmartin
./wdqs_terms_english.sh saw+fish
./wdqs_terms_english.sh Sawfish
./wdqs_terms_english.sh Scallop
./wdqs_terms_english.sh Schistus
./wdqs_terms_english.sh Schout+by+Nacht
./wdqs_terms_english.sh screw
./wdqs_terms_english.sh sea+hedgehog
./wdqs_terms_english.sh Sea+crow
./wdqs_terms_english.sh Sea+devil
./wdqs_terms_english.sh sea+eagle
./wdqs_terms_english.sh sea+ear
./wdqs_terms_english.sh Sea+egg
./wdqs_terms_english.sh Sea+horse
./wdqs_terms_english.sh Sea+lark
./wdqs_terms_english.sh sea+muscle
./wdqs_terms_english.sh sea+otter
./wdqs_terms_english.sh sea+pie
./wdqs_terms_english.sh Sea+turtle
./wdqs_terms_english.sh Seal
./wdqs_terms_english.sh Shad
./wdqs_terms_english.sh Shaker
./wdqs_terms_english.sh Shark
./wdqs_terms_english.sh shea+toulou
./wdqs_terms_english.sh Sheep
./wdqs_terms_english.sh Sheldappel
./wdqs_terms_english.sh sheldapple
./wdqs_terms_english.sh Shepherd
./wdqs_terms_english.sh shock
./wdqs_terms_english.sh shore+bird
./wdqs_terms_english.sh Shorebird
./wdqs_terms_english.sh Shoveler
./wdqs_terms_english.sh Shrew
./wdqs_terms_english.sh Shrike
./wdqs_terms_english.sh Shrimp
./wdqs_terms_english.sh Shrite
./wdqs_terms_english.sh silver
./wdqs_terms_english.sh silver+bird
./wdqs_terms_english.sh Siskin
./wdqs_terms_english.sh Skate
./wdqs_terms_english.sh Skunk
./wdqs_terms_english.sh sky+lark
./wdqs_terms_english.sh Slate
./wdqs_terms_english.sh Slickensides
./wdqs_terms_english.sh Sloth
./wdqs_terms_english.sh Slow+worm
./wdqs_terms_english.sh Slug
./wdqs_terms_english.sh Smelt
./wdqs_terms_english.sh Smiris
./wdqs_terms_english.sh Snail
./wdqs_terms_english.sh Snake+stones
./wdqs_terms_english.sh Snipe
./wdqs_terms_english.sh snow+bunting
./wdqs_terms_english.sh Snow+bunting
./wdqs_terms_english.sh Soap+stone
./wdqs_terms_english.sh Soland+goose
./wdqs_terms_english.sh song+thrush
./wdqs_terms_english.sh Sparrow
./wdqs_terms_english.sh Sparrow+bawk
./wdqs_terms_english.sh sparrow+hawk
./wdqs_terms_english.sh Spelter
./wdqs_terms_english.sh Spider
./wdqs_terms_english.sh spoon+bill
./wdqs_terms_english.sh Spoonbill
./wdqs_terms_english.sh Sprat
./wdqs_terms_english.sh Spring+tail
./wdqs_terms_english.sh Squid
./wdqs_terms_english.sh Squirrel
./wdqs_terms_english.sh Stag
./wdqs_terms_english.sh Stag+beatle
./wdqs_terms_english.sh stair+case
./wdqs_terms_english.sh star+gazer
./wdqs_terms_english.sh Stare
./wdqs_terms_english.sh Stargazer
./wdqs_terms_english.sh Sterling
./wdqs_terms_english.sh Stickleback
./wdqs_terms_english.sh sting+ray
./wdqs_terms_english.sh Stoat
./wdqs_terms_english.sh stonemarrow
./wdqs_terms_english.sh Storck
./wdqs_terms_english.sh stork
./wdqs_terms_english.sh Storm+finch
./wdqs_terms_english.sh stream+tin
./wdqs_terms_english.sh stream+works
./wdqs_terms_english.sh Sturgeon
./wdqs_terms_english.sh Sucking+fish
./wdqs_terms_english.sh sucking+fisch
./wdqs_terms_english.sh Sulfur
./wdqs_terms_english.sh Sun+fish
./wdqs_terms_english.sh Swallow
./wdqs_terms_english.sh Swan
./wdqs_terms_english.sh Swan+goose
./wdqs_terms_english.sh swan+goose
./wdqs_terms_english.sh Swift
./wdqs_terms_english.sh sword+fish
./wdqs_terms_english.sh Swordfish
./wdqs_terms_english.sh Syenites
./wdqs_terms_english.sh Tape+worm
./wdqs_terms_english.sh tape+worm
./wdqs_terms_english.sh Tarrock
./wdqs_terms_english.sh Tench
./wdqs_terms_english.sh Thistle+finch
./wdqs_terms_english.sh thistlefinch
./wdqs_terms_english.sh Throstle
./wdqs_terms_english.sh Thrush
./wdqs_terms_english.sh thunder+stones
./wdqs_terms_english.sh Tick
./wdqs_terms_english.sh tin+glass
./wdqs_terms_english.sh Titmouse
./wdqs_terms_english.sh Toad
./wdqs_terms_english.sh Toad+stone
./wdqs_terms_english.sh toadpoles
./wdqs_terms_english.sh Toadstone
./wdqs_terms_english.sh tooth+shell
./wdqs_terms_english.sh topshell
./wdqs_terms_english.sh Tortoiseshell+cat
./wdqs_terms_english.sh tropic+bird
./wdqs_terms_english.sh Trout
./wdqs_terms_english.sh trussed+fowl
./wdqs_terms_english.sh Tumbler
./wdqs_terms_english.sh Tunny
./wdqs_terms_english.sh Turbit
./wdqs_terms_english.sh Turbot
./wdqs_terms_english.sh Turkey
./wdqs_terms_english.sh turnspit
./wdqs_terms_english.sh Turtle
./wdqs_terms_english.sh Turtle+dove
./wdqs_terms_english.sh turtle+dove
./wdqs_terms_english.sh Venus´s+ear
./wdqs_terms_english.sh Wad
./wdqs_terms_english.sh Wall+louse
./wdqs_terms_english.sh walrus
./wdqs_terms_english.sh Wasp
./wdqs_terms_english.sh water+dog
./wdqs_terms_english.sh Water+moth
./wdqs_terms_english.sh watering+pot
./wdqs_terms_english.sh Waxen+vein
./wdqs_terms_english.sh Weesel
./wdqs_terms_english.sh Wever
./wdqs_terms_english.sh Whale
./wdqs_terms_english.sh Whale+killer
./wdqs_terms_english.sh whale+killer
./wdqs_terms_english.sh Wheel+animal
./wdqs_terms_english.sh wheel+animal
./wdqs_terms_english.sh whelk
./wdqs_terms_english.sh Whet+stone
./wdqs_terms_english.sh whidah
./wdqs_terms_english.sh whidah+bird
./wdqs_terms_english.sh whirl
./wdqs_terms_english.sh white+ant
./wdqs_terms_english.sh white+game
./wdqs_terms_english.sh white+shark
./wdqs_terms_english.sh white+waterwagtail
./wdqs_terms_english.sh white+whale
./wdqs_terms_english.sh Whiting
./wdqs_terms_english.sh Wild+boar
./wdqs_terms_english.sh Wood+cock
./wdqs_terms_english.sh Wood+cracker
./wdqs_terms_english.sh Wood+louse
./wdqs_terms_english.sh Wood+pecker
./wdqs_terms_english.sh Wood+tin
./wdqs_terms_english.sh Wood+ant
./wdqs_terms_english.sh wood+louse
./wdqs_terms_english.sh wood+tin
./wdqs_terms_english.sh woodcock
./wdqs_terms_english.sh woodcracker
./wdqs_terms_english.sh woodpecker
./wdqs_terms_english.sh wormshell
./wdqs_terms_english.sh wreath
./wdqs_terms_english.sh Wren
./wdqs_terms_english.sh Wry+neck
./wdqs_terms_english.sh wryneck
./wdqs_terms_english.sh yellow+kammer
./wdqs_terms_english.sh Zircon
